toolbar:
  - styleselect | bold italic | link image | undo redo | fontsizeselect
  - table | fullscreen
plugins:
  - table
  - fullscreen
setup :
  function(ed) {
    ed.on('init', function()
    {
        this.getDoc().body.style.fontSize = '17px';
    });
  }